### ISSUE TITLE
slopper error at stage 3

### ISSUE THREAD

**Issue by fayweili** [wenzelm/slidr-sloppr#3]
oops. Me again! So the slopper pipeline finished with my data, but I got an error message in `SL.featureCounts.genes.log.txt`: 

```
Error in min(Y) >= 0 : 
  only defined on a data frame with all numeric variables
Calls: sl_clusters ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

**The log:** 
```
[2021-02-02 11:50:24] >>> Loading dependencies
[2021-02-02 11:50:24] >>> STAGE 1: SL read identification
[2021-02-02 11:50:24] Converting GFF to GTF ...
[2021-02-02 11:50:25] Extracting unique exons from GTF ...
[2021-02-02 11:50:29] Generating HISAT2 index ...
[2021-02-02 11:50:48] >>> Processing library data
[2021-02-02 11:50:48] Aligning reads to genome ...
[2021-02-02 12:01:36] 66.93% overall alignment rate
[2021-02-02 12:01:42] Inferred library strandedness: 1
[2021-02-02 12:01:43] Extracting candidate reads ...
[2021-02-02 12:03:17] Found 629053 candidate read(pair)s ...
[2021-02-02 12:03:17] Screening candidate reads for spliced leaders ...
[2021-02-02 12:03:52] 111,602 (17.7%) SL tails found among candidate reads
[2021-02-02 12:03:52] Aligning 64315 C73_1 reads ...
[2021-02-02 12:03:53] Aligning 47287 C73_2 reads ...
[2021-02-02 12:03:54] Aligning untrimmed reads ...
[2021-02-02 12:04:05] Quantifying background gene coverage ...
[2021-02-02 12:04:24] Quantifying untrimmed reads ...
[2021-02-02 12:04:27] Merging SL BAM files ...
[2021-02-02 12:04:28] >>> STAGE 2: SL quantification
[2021-02-02 12:04:28] Quantifying SL reads against genes ...
[2021-02-02 12:04:28] Quantifying SL reads against exons ...
[2021-02-02 12:04:29] Curating gene annotations ...
bg.featureCounts.genes.raw.txt: 13969 gene records comprising 13969 gene IDs ...
un.featureCounts.genes.raw.txt: 13969 gene records comprising 13969 gene IDs ...
SL.featureCounts.genes.raw.txt: 13969 gene records comprising 13969 gene IDs ...
Processed 121956 exon records comprising 13969 gene IDs ...
Gained 0 gene IDs (13969 total) by resolving internal exon peaks ...
[2021-02-02 12:05:17] >>> STAGE 3: Operon prediction
[2021-02-02 12:05:17] Predicting operons ...
Processing counts data from SLOPPR_2021-02-02_11-50-24/2-counts/SL.featureCounts.genes.clean.txt ...
SL1-type SLs:

SL2-type SLs:
                C73_1
                C73_2
Identifying SL clusters ...
```

**Screenshot of my folder content**
<img width="753" alt="image" src="https://user-images.githubusercontent.com/38337424/106642121-f7443500-6555-11eb-8289-76d2c4dad978.png">

**Comment by wenzelm** [comment]
The clustering algorithm failed because you only have two data points (1 library x 2 SLs). I did anticipate such situations in the code, but clearly your data slipped through the sanity check. Could you please paste the first 10 lines or so of the three 2-counts/*.featureCounts.genes.clean.txt files? I'll take a look tonight or tomorrow. Sorry about the trouble.

**Comment by fayweili** [comment]
**SL.featureCounts.gene.clean.txt:**
```
Geneid	Chr	Start	End	Strand	Length	SLOPPR_2021.02.02_11.50.24.1.library_data.C73_1.fc.bam	SLOPPR_2021.02.02_11.50.24.1.library_data.C73_2.fc.bam
Monodopsis_C73_contig_1_g00010	Monodopsis_C73_contig_1	18365	20109	-	1744	0	0
Monodopsis_C73_contig_1_g00020	Monodopsis_C73_contig_1	20175	23533	+	3358	0	0
Monodopsis_C73_contig_1_g00030	Monodopsis_C73_contig_1	24276	31200	+	6924	0	0
Monodopsis_C73_contig_1_g00040	Monodopsis_C73_contig_1	32169	35529	-	3360	0	0
Monodopsis_C73_contig_1_g00050	Monodopsis_C73_contig_1	35744	38274	-	2530	0	0
Monodopsis_C73_contig_1_g00060	Monodopsis_C73_contig_1	38873	39777	+	904	0	0
Monodopsis_C73_contig_1_g00070	Monodopsis_C73_contig_1	42089	51432	-	9343	0	0
Monodopsis_C73_contig_1_g00080	Monodopsis_C73_contig_1	58985	65748	-	6763	0	0
Monodopsis_C73_contig_1_g00090	Monodopsis_C73_contig_1	66918	73170	+	6252	0	0
```

**bg.featureCounts.gene.clean.txt:**
```
Geneid	Chr	Start	End	Strand	Length	SLOPPR_2021.02.02_11.50.24.1.library_data.end2end_pre.align.bam
Monodopsis_C73_contig_1_g00010	Monodopsis_C73_contig_1	18365	20109	-	1744	552
Monodopsis_C73_contig_1_g00020	Monodopsis_C73_contig_1	20175	23533	+	3358	254
Monodopsis_C73_contig_1_g00030	Monodopsis_C73_contig_1	24276	31200	+	6924	5661
Monodopsis_C73_contig_1_g00040	Monodopsis_C73_contig_1	32169	35529	-	3360	188
Monodopsis_C73_contig_1_g00050	Monodopsis_C73_contig_1	35744	38274	-	2530	186
Monodopsis_C73_contig_1_g00060	Monodopsis_C73_contig_1	38873	39777	+	904	30
Monodopsis_C73_contig_1_g00070	Monodopsis_C73_contig_1	42089	51432	-	9343	983
Monodopsis_C73_contig_1_g00080	Monodopsis_C73_contig_1	58985	65748	-	6763	1479
Monodopsis_C73_contig_1_g00090	Monodopsis_C73_contig_1	66918	73170	+	6252	4773
```

**un.featureCounts.gene.clean.txt:**
```
Geneid	Chr	Start	End	Strand	Length	SLOPPR_2021.02.02_11.50.24.1.library_data.untrimmed.bam
Monodopsis_C73_contig_1_g00010	Monodopsis_C73_contig_1	18365	20109	-	1744	8
Monodopsis_C73_contig_1_g00020	Monodopsis_C73_contig_1	20175	23533	+	3358	5
Monodopsis_C73_contig_1_g00030	Monodopsis_C73_contig_1	24276	31200	+	6924	78
Monodopsis_C73_contig_1_g00040	Monodopsis_C73_contig_1	32169	35529	-	3360	3
Monodopsis_C73_contig_1_g00050	Monodopsis_C73_contig_1	35744	38274	-	2530	3
Monodopsis_C73_contig_1_g00060	Monodopsis_C73_contig_1	38873	39777	+	904	0
Monodopsis_C73_contig_1_g00070	Monodopsis_C73_contig_1	42089	51432	-	9343	21
Monodopsis_C73_contig_1_g00080	Monodopsis_C73_contig_1	58985	65748	-	6763	36
Monodopsis_C73_contig_1_g00090	Monodopsis_C73_contig_1	66918	73170	+	6252	50
```

**Comment by wenzelm** [comment]
Thank you. The code runs fine on my end using these data. I'm not sure which function threw this error, so I've updated the code to print a few diagnostics before this error occurs. Could you please run the latest code and paste the output on screen? Thank you for your patience.

**Comment by fayweili** [comment]
Still the same error in `SL.featureCounts.genes.log.txt`. Here is buffer:

```
[2021-02-11 13:29:25] >>> Loading dependencies
[2021-02-11 13:29:25] >>> STAGE 1: SL read identification
[2021-02-11 13:29:25] Converting GFF to GTF ...
[2021-02-11 13:29:25] Extracting unique exons from GTF ...
[2021-02-11 13:29:29] Generating HISAT2 index ...
[2021-02-11 13:29:48] >>> Processing library data
[2021-02-11 13:29:48] Aligning reads to genome ...
[2021-02-11 13:42:21] 66.93% overall alignment rate
[2021-02-11 13:42:27] Inferred library strandedness: 1
[2021-02-11 13:42:27] Extracting candidate reads ...
[2021-02-11 13:44:05] Found 629093 candidate read(pair)s ...
[2021-02-11 13:44:05] Screening candidate reads for spliced leaders ...
[2021-02-11 13:44:39] 111,599 (17.7%) SL tails found among candidate reads
[2021-02-11 13:44:39] Aligning 64313 C73_1 reads ...
[2021-02-11 13:44:40] Aligning 47286 C73_2 reads ...
[2021-02-11 13:44:41] Aligning untrimmed reads ...
[2021-02-11 13:44:49] Quantifying background gene coverage ...
[2021-02-11 13:45:00] Quantifying untrimmed reads ...
[2021-02-11 13:45:03] Merging SL BAM files ...
[2021-02-11 13:45:04] >>> STAGE 2: SL quantification
[2021-02-11 13:45:04] Quantifying SL reads against genes ...
[2021-02-11 13:45:04] Quantifying SL reads against exons ...
[2021-02-11 13:45:05] Curating gene annotations ...
bg.featureCounts.genes.raw.txt: 13969 gene records comprising 13969 gene IDs ...
un.featureCounts.genes.raw.txt: 13969 gene records comprising 13969 gene IDs ...
SL.featureCounts.genes.raw.txt: 13969 gene records comprising 13969 gene IDs ...
Processed 121956 exon records comprising 13969 gene IDs ...
Gained 0 gene IDs (13969 total) by resolving internal exon peaks ...
[2021-02-11 13:45:51] >>> STAGE 3: Operon prediction
[2021-02-11 13:45:51] Predicting operons ...
Processing counts data from SLOPPR_2021-02-11_13-29-25/2-counts/SL.featureCounts.genes.clean.txt ...
SL1-type SLs:

SL2-type SLs:
                C73_1
                C73_2
Identifying SL clusters ... [1] ID      Library SL      SL.type Reads
<0 rows> (or 0-length row.names)
[1] 0 0
```

**Comment by wenzelm** [comment]
OK, looks like some stage is throwing all your samples out for clustering. Could you please zip up the 2-counts directory and send it to my email marius.wenzel@abdn.ac.uk? I'll take a look asap and fix this for you. Thank you.

**Comment by fayweili** [comment]
So with the newest sloppr update, I got something in the 3-* folder. However in `SL.featureCounts.genes.log.txt`, there is this error message: 
```
Error in label_number(accuracy = 1, big.mark = ",") : 
  could not find function "label_number"
Calls: scale_y_log10 ... scale_y_continuous -> continuous_scale -> check_breaks_labels
Execution halted
```  

<img width="440" alt="image" src="https://user-images.githubusercontent.com/38337424/107996903-89652800-6faf-11eb-8210-ed85ee908fd1.png">

**Comment by wenzelm** [comment]
You need the scales R package (I thought this came with ggplot2, but perhaps not).
Launch R and type install.packages(“scales”)

Then rerun the command.

**Comment by fayweili** [comment]
ok! NOW I GOT ALL THE RESULTS!!
